services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CI=true
      - BASE_URL=${BASE_URL:-https://www.saucedemo.com}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    ipc: host
    command: npm test

jenkins:
  build:
    context: .
    dockerfile: Dockerfile.jenkins
  container_name: jenkins-local
  privileged: true
  user: root
  ports:
    - '8080:8080'
    - '50000:50000'
  volumes:
    - jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
